from os import getenv

CONSUMER_KEY = getenv("CONSUMER_KEY")
CONSUMER_SECRET = getenv("CONSUMER_SECRET")
ACCESS_KEY = getenv("ACCESS_KEY")
ACCESS_SECRET = getenv("ACCESS_SECRET")

TWITTER_ID = getenv("TWITTER_ID")

RETRIEVED_TWEETS_FILE = getenv("RETRIEVED_TWEETS_FILE")
FIXED_TWEETS_FILE = getenv("FIXED_TWEETS_FILE")

INPUT_TEXT_SEQ_LENGTH = getenv("INPUT_TEXT_SEQ_LENGTH")

TWEET_INTERVAL_SECONDS = getenv("TWEET_INTERVAL_SECONDS")
